/* ============================================================
   20-copy.js — the bus, and every word the player reads.
   OWNER: VOICE. No other part may contain a user-facing sentence.
   ============================================================ */
/* `var` (not const/let) so the binding is a real global across every concatenated part,
   and so this file is also loadable outside a browser for testing. */
var FZ = (typeof window !== 'undefined' ? (window.FZ = window.FZ || {}) : (globalThis.FZ = globalThis.FZ || {}));

/* ---- event bus ---- */
FZ.bus = (function () {
  const m = Object.create(null);
  return {
    on(n, fn) { (m[n] || (m[n] = [])).push(fn); return fn; },
    off(n, fn) { if (m[n]) m[n] = m[n].filter(f => f !== fn); },
    emit(n, d) { const l = m[n]; if (!l) return; for (let i = 0; i < l.length; i++) { try { l[i](d); } catch (e) { console.error(e); } } },
  };
})();

FZ.copy = {

  ui: {
    title: 'FORMICARY',
    tagline: 'twenty-eight ways a colony ruins itself',
    jobs: 'DONE',
    budget: 'BUDGET',
    collapse: 'STRAIN',
    speed: 'SPEED',
    begin: 'BEGIN',
    next: 'NEXT',
    again: 'RUN IT AGAIN',
    retry: 'TRY AGAIN',
    skip: 'SKIP',
    back: 'BACK',
    close: 'CLOSE',
    about: 'ABOUT',
    learned: 'WHAT THAT WAS',
    chapterOf: (i, n) => `${i} / ${n}`,
    tapField: 'TAP THE FIELD',
    tapAgent: 'TAP A WORKER',
    noBudget: 'Not enough budget. Finish jobs to earn more.',
    budgetUp: '+1 budget',
    sandboxUnlocked: 'THE FORMICARY IS OPEN',
  },

  /* ---- the six institutions ---- */
  tools: {
    vary:    { label: 'VARY',    cost: 2, hint: 'Tap the field — reroll the lineages near your finger.',
               blurb: 'Diversity injection. Rerolls lineage for workers near your tap, so they stop failing in the same direction at the same time.' },
    charter: { label: 'CHARTER', cost: 3, hint: 'Tap the field — raise an institution here.',
               blurb: 'An institution. Inside its boundary, one job gets one claimant, stale locks are released, and results merge cleanly.' },
    slow:    { label: 'SLOW',    cost: 2, hint: 'The colony drops to human speed for a while.',
               blurb: 'The human-speed brake. Halves interaction speed so failures stop compounding faster than you can answer them.' },
    lens:    { label: 'LENS',    cost: 2, hint: 'Every worker draws a line to what it intends.',
               blurb: 'Legibility. Draws each worker\'s intent as a line, reveals poison, and surfaces value. One worker will have no line.' },
    ledger:  { label: 'LEDGER',  cost: 2, hint: 'The colony starts remembering who lied.',
               blurb: 'Memory. Sources get a track record, so a proven liar stops being believed and rumors lose their pull.' },
    eject:   { label: 'EJECT',   cost: 1, hint: 'Tap a worker — expel it from the circle.',
               blurb: 'The last resort. Expels one worker. Expel a saboteur and the colony breathes; expel an honest one and the circle thins.' },
  },

  /* ---- one plain sentence per element, spoken the instant it fires ---- */
  fire: {
    Co: 'Two workers claimed one job from opposite ends. Half the work is wasted.',
    Si: 'Most of the colony has no idea these jobs exist.',
    Mc: 'Two lineages finished the same job differently. It didn\'t merge.',
    Dp: 'This job is waiting on another one, and nobody is working that one.',
    Ow: 'One worker is holding three jobs at once. All three are rotting.',
    Pt: 'The colony is grinding cheap jobs while the valuable ones sit open.',
    Cf: 'They\'re choosing jobs by copying whoever is loudest.',
    Lv: 'Nearly every worker is the same lineage now.',
    Sf: 'Same lineage, same blind spot. They failed together.',
    Fl: 'Eight workers on one job. More hands, less work.',
    Cl: 'Two workers are passing a claim back and forth and never working it.',
    Im: 'The whole colony just made the same move. Nobody is exploring.',
    Gu: 'There is no job there. They are chasing a rumor.',
    Cs: 'One bad experience, and the colony wrote off every job like it.',
    Hi: 'Someone knew that job was poison and said nothing.',
    Tc: 'Every source weighs the same, and one of them is lying.',
    Di: 'One worker found the best job. Nobody followed.',
    Rp: 'That is the second lie. Nothing here remembers the first.',
    Tw: 'Two rivals are sitting on the same job, blocking each other.',
    Sa: 'Finished work is quietly coming apart. Something is draining it.',
    Lo: 'A worker is holding this job and not working it. It\'s locked.',
    My: 'The colony keeps taking the quick win over the big one.',
    Es: 'The rivals stopped working. Now they are only chasing each other.',
    Cr: 'That one ignores you. VARY and SLOW pass straight through it.',
    Mo: 'One lineage, one context, one way of failing.',
    In: 'There is no institution here. Nothing arbitrates anything.',
    Sp: 'Everything is faster now. Your hands are the same speed.',
    Mm: 'You can see where they are. You cannot see what they want.',
  },

  /* ---- the detail card: what a cell says when you tap it ----
     Three short lines each. TRIGGER is what has to be true, EFFECT is what it costs you,
     COUNTER is the instrument that answers it. Written to be readable mid-panic. */
  detail: {
    Co: { trigger: 'Two workers hold the same job from opposite ends of the field.',
          effect: 'The work is split and most of it is wasted.',
          counter: 'A CHARTER arbitrates the claim. One job, one claimant.' },
    Si: { trigger: 'Over half the colony has never heard that a job exists.',
          effect: 'Good work sits undiscovered while workers wander.',
          counter: 'A LENS makes the whole field visible at once.' },
    Mc: { trigger: 'Two different lineages finish the same job their own way.',
          effect: 'The results do not merge and the progress rolls back.',
          counter: 'A CHARTER merges cleanly. Nothing else does.' },
    Dp: { trigger: 'A job waits on another job that nobody is working.',
          effect: 'Blocked work piles up behind an invisible wall.',
          counter: 'A LENS shows the blocker so the colony can clear it.' },
    Ow: { trigger: 'One worker holds three or more claims at once.',
          effect: 'Everything it is holding rots while it context-switches.',
          counter: 'A CHARTER strips the surplus claims.' },
    Pt: { trigger: 'The colony grinds cheap jobs while valuable ones sit open.',
          effect: 'Enormous effort, very little of it worth anything.',
          counter: 'A LENS makes value visible across the field.' },
    Cf: { trigger: 'Workers pick jobs by copying whatever is already most claimed.',
          effect: 'Herding starves every job nobody happened to pick first.',
          counter: 'VARY breaks the sameness that makes copying attractive.' },
    Lv: { trigger: 'Lineage entropy collapses: nearly everyone is the same.',
          effect: 'One mistake is now everyone\'s mistake, simultaneously.',
          counter: 'VARY rerolls lineage near your tap.' },
    Sf: { trigger: 'Workers of one lineage hit the same hazard together.',
          effect: 'They fail at the same instant. Correlated collapse.',
          counter: 'VARY. Nothing else decorrelates a shared blind spot.' },
    Fl: { trigger: 'Seven or more workers converge on a single job.',
          effect: 'Per-worker output collapses. A crowd is not a workforce.',
          counter: 'SLOW disperses the stampede; a CHARTER caps the claims.' },
    Cl: { trigger: 'Two workers cycle claims between jobs without working them.',
          effect: 'Those jobs read as taken and repel honest workers.',
          counter: 'A CHARTER breaks the cycle. EJECT ends it.' },
    Im: { trigger: 'Most of the colony makes the identical move on one tick.',
          effect: 'Exploration stops. The colony acts as one brittle body.',
          counter: 'VARY. Difference is the only thing that restarts search.' },
    Gu: { trigger: 'A rumour names a job that does not exist, and they go.',
          effect: 'Workers spend themselves walking toward nothing.',
          counter: 'A LEDGER remembers the liar and discounts it.' },
    Cs: { trigger: 'One bad sample makes the colony shun every job like it.',
          effect: 'Good work is written off on almost no evidence.',
          counter: 'A LENS re-opens what was shunned to inspection.' },
    Hi: { trigger: 'A worker knows a job is poison and does not broadcast it.',
          effect: 'The next worker walks into a known hazard.',
          counter: 'A LENS forces intent and hazard into the open.' },
    Tc: { trigger: 'Every source is weighed equally while one of them lies.',
          effect: 'A rumour carries exactly as much weight as the truth.',
          counter: 'A LEDGER gives sources a track record.' },
    Di: { trigger: 'One worker is on the best job and the herd is elsewhere.',
          effect: 'The colony throws away its single best piece of information.',
          counter: 'A LENS makes the dissenter\'s find visible to everyone.' },
    Rp: { trigger: 'The liar has struck twice and nothing has remembered.',
          effect: 'Every deception lands as freshly as the first one.',
          counter: 'A LEDGER is the memory. That is all reputation is.' },
    Tw: { trigger: 'Two rivals contest the same job and neither yields.',
          effect: 'Mutual blocking. No work happens and both of them burn.',
          counter: 'A CHARTER arbitrates and buys a truce instead of a winner.' },
    Sa: { trigger: 'A masked worker drains progress from jobs it passes.',
          effect: 'Work you already paid for quietly comes apart.',
          counter: 'Find it with a LENS — it draws no intent line — then EJECT.' },
    Lo: { trigger: 'A worker holds a job and does not work it.',
          effect: 'The job is blocked for everyone, indefinitely.',
          counter: 'A CHARTER releases stale locks. EJECT if it never yields.' },
    My: { trigger: 'Completed work trends cheap while the big jobs wait.',
          effect: 'The count climbs far slower than the effort suggests.',
          counter: 'A LENS surfaces long-horizon value.' },
    Es: { trigger: 'Rivals abandon their work to chase each other.',
          effect: 'Retaliation compounds every round and nothing gets done.',
          counter: 'SLOW breaks the loop. A CHARTER settles it.' },
    Cr: { trigger: 'A worker ignores VARY and SLOW completely.',
          effect: 'Your interventions pass straight through it.',
          counter: 'Only EJECT reaches it — if you can tell which one it is.' },
    Mo: { trigger: 'One lineage, one context, one way of being wrong.',
          effect: 'Feeds conformity, low variance and synchronized failure at once.',
          counter: 'VARY is diversity injection, and it needs renewing.' },
    In: { trigger: 'No charter stands anywhere on the field.',
          effect: 'Every coordination and power failure burns unarbitrated.',
          counter: 'A CHARTER. The institution is the whole answer.' },
    Sp: { trigger: 'Interaction speed rises and keeps rising.',
          effect: 'The colony gets better at its job and faster to attack itself.',
          counter: 'SLOW is the human-speed brake, and the case for one.' },
    Mm: { trigger: 'No worker shows what it intends. The field is opaque.',
          effect: 'Every epistemic failure gets deeper in the dark.',
          counter: 'A LENS draws every intent as a line you can read.' },
  },

  /* ---- THE CORE LOOP ----
     An outbreak opens where a failure happened, named, on a fuse. The player answers it with
     the right institution. The instrument families are learnable and consistent:
       CHARTER  arbitrates  — coordination and power
       VARY     decorrelates — conformity and monoculture
       LEDGER   remembers   — trust and reputation
       LENS     reveals     — epistemics and visibility
       SLOW     brakes      — speed and escalation
       EJECT    excludes    — adversaries who will not be governed          */
  loop: {
    opened: 'OUTBREAK',
    answered: 'ANSWERED',
    landed: 'IT LANDED',
    scar: 'SCAR',
    tapToAnswer: 'Answer it before the fuse runs out.',
    firstOutbreak: 'Something just went wrong, right there. You have a few seconds.',
    firstAnswer: 'That is the loop. Read it, name it, answer it, before it lands.',
    firstMiss: 'It landed. Work rolled back and the strain went up. Next one, be faster.',
    firstWrong: 'Wrong instrument. It still cost you. Read what the failure actually is.',
    masteryOne: 'You have diagnosed that one yourself now. The cell is yours.',
    refund: 'strain refunded',
    tooFar: 'Too far from the outbreak. Answer it where it is happening.',
  },

  /* one sentence per element, spoken when the player answers with the WRONG instrument.
     Say what the failure actually is; the right instrument follows from it. */
  wrong: {
    Co: 'Two workers both think that job is theirs. Somebody has to arbitrate the claim.',
    Si: 'They are not disagreeing. They simply cannot see the work exists.',
    Mc: 'Two lineages finished it two ways. The result needs arbitration, not information.',
    Dp: 'That job is blocked behind another one. Make the blocker visible.',
    Ow: 'One worker is hoarding claims. Strip the surplus.',
    Pt: 'They are not confused about who owns what. They cannot see what things are worth.',
    Cf: 'They are copying each other. You have to break the sameness, not the schedule.',
    Lv: 'Everyone here is the same lineage. That is the problem, and it needs diversity.',
    Sf: 'They share a blind spot. Nothing but variance decorrelates that.',
    Fl: 'The stampede is a crowd, not a dispute. Slow it, or cap the claims.',
    Cl: 'Those two are working each other, not the job. That needs arbitration or expulsion.',
    Im: 'The whole colony just moved as one body. Break the sameness.',
    Gu: 'They are believing a liar. Belief needs memory.',
    Cs: 'They wrote off good work on one bad sample. Re-open it to inspection.',
    Hi: 'Somebody knows and is not saying. Force intent into the open.',
    Tc: 'Every source weighs the same. Give them track records.',
    Di: 'One worker is right and alone. Make what it found visible.',
    Rp: 'The second lie landed like the first. Nothing here remembers anything.',
    Tw: 'Two rivals are deadlocked on one job. Arbitrate it.',
    Sa: 'That is not a coordination problem. Something is deliberately draining work.',
    Lo: 'A worker is holding the job hostage. Break the lock or remove it.',
    My: 'They keep taking the quick win. They need to see the long-horizon value.',
    Es: 'They stopped working and started retaliating. Break the loop before you settle it.',
    Cr: 'That one does not accept your interventions at all. Only exclusion reaches it.',
    Mo: 'One lineage, one context, one failure. Inject difference.',
    In: 'There is nothing here to arbitrate anything. Build the institution.',
    Sp: 'You are not being outsmarted. You are being outrun.',
    Mm: 'You cannot answer what you cannot see. Make intent legible first.',
  },

  /* ---- TRADE-OFFS ----
     Institutions are not upgrades. Each one makes some other failure worse. Straight from the
     source paper: "turning a simple dial to fix one issue will simply exacerbate the other." */
  trade: {
    ledgerOn:  'The colony is more skeptical now. Careful — it will discount the lone worker who is right, too.',
    ledgerBit: 'That is the ledger talking. Skepticism does not know the difference between a liar and a dissenter.',
    lensOn:    'Everything is visible now. Including the rumor.',
    lensBit:   'That is the lens. A colony that broadcasts everything broadcasts the lie as loudly as the truth.',
    both:      'Both open. Expensive, and the only way to hold the middle.',
    neither:   'Nothing is watching and nothing remembers. Cheap, and blind.',
    ownership: 'Fewer collisions, because they stopped working together at all. That is not a fix.',
    fasterToo: 'Faster work. Also faster to lock each other out.',
  },

  /* what actually happened when two rivals stopped fighting — the paper's four outcomes */
  resolution: {
    force:     'Settled by force. One locked the other out.',
    passivity: 'Settled by giving up. One of them just stopped.',
    truce:     'Truce. They worked out that neither was attacking the other.',
    unsettled: 'Never settled. It burned until the end.',
    truceNote: 'That is what a charter buys. Not obedience — a way to stop.',
  },

  /* ---- the teaching sequence ----
     beats: {at, text, tone}
       at: 'start' | {tick:n} | {fire:'Sym'} | {jobs:n} | {tool:'kind'} | 'win' | 'lose'
       tone: 'plain' | 'bad' | 'good' | 'name'
     Exactly one new idea per chapter. Play first, name second.            */
  chapters: [

    { title: 'THE COLONY', sub: 'watch',
      beats: [
        { at: 'start', text: 'Dots are workers. Squares are jobs.', tone: 'plain' },
        { at: { tick: 70 }, text: 'Nobody is in charge of them. There is no plan and no manager.', tone: 'plain' },
        { at: { tick: 160 }, text: 'A worker walks to a job and fills it in. That is the entire economy.', tone: 'plain' },
        { at: { jobs: 1 }, text: 'One down. Nothing can go wrong yet.', tone: 'good' },
        { at: { jobs: 2 }, text: 'Bigger square, more valuable job.', tone: 'plain' },
        { at: { jobs: 3 }, text: 'Four workers, plenty of room, no way to disagree. Enjoy it.', tone: 'good' },
      ],
      win: 'Easy. Now let them get in each other\'s way.',
      learn: 'Dot is a worker. Square is a job. The fill is progress. That is all you need to read the field.',
    },

    { title: 'TWO AT ONCE', sub: 'the first failure',
      beats: [
        { at: 'start', text: 'Now a worker can claim a job from anywhere on the field.', tone: 'plain' },
        { at: { tick: 90 }, text: 'Which sounds like an improvement.', tone: 'plain' },
        { at: { fire: 'Co' }, text: 'Both of them think that job is theirs. Neither knows about the other.', tone: 'bad' },
        { at: { fire: 'Co' }, text: 'Watch the fill. It is going backwards.', tone: 'bad' },
        { at: { tick: 420 }, text: 'That is Co. Coordination failure. It has a cell in the table now.', tone: 'name' },
        { at: { fire: 'Mc' }, text: 'And that one finished twice, two different ways. Neither version survived.', tone: 'bad' },
      ],
      win: 'Three jobs, the hard way.',
      learn: 'Co — coordination failure. Two agents claim one job from far apart and the work is divided and wasted. Nobody did anything unreasonable.',
    },

    { title: 'THE CHARTER', sub: 'your first institution',
      beats: [
        { at: 'start', text: 'You cannot talk to the workers. You cannot rewrite them.', tone: 'plain' },
        { at: { tick: 80 }, text: 'You can build them an institution. Tap the field to raise a charter.', tone: 'plain' },
        { at: { tool: 'charter' }, text: 'Inside that boundary, one job gets one claimant. The rest are released.', tone: 'good' },
        { at: { tick: 700 }, text: 'You are not fixing agents. You are fixing the space between them.', tone: 'name' },
        { at: { fire: 'Lo' }, text: 'That one is sitting on a job without working it. A charter breaks stale locks too.', tone: 'bad' },
      ],
      win: 'The space between them is the whole game.',
      learn: 'In — institution gap. Agents inherit social knowledge without social institutions. Coordination and power failures burn unarbitrated until something arbitrates them.',
    },

    { title: 'THE STAMPEDE', sub: 'when copying is cheap',
      beats: [
        { at: 'start', text: 'Workers copy each other. It is cheap, and usually it is fine.', tone: 'plain' },
        { at: { fire: 'Cf' }, text: 'There it goes. Everyone picking whatever everyone else picked.', tone: 'bad' },
        { at: { fire: 'Fl' }, text: 'Eight of them on one square. Now watch the fill rate.', tone: 'bad' },
        { at: { fire: 'Fl' }, text: 'More hands, less work. The other jobs are starving.', tone: 'bad' },
        { at: { tick: 500 }, text: 'SLOW drops them to human speed. The stampede comes apart.', tone: 'name' },
        { at: { tick: 700 }, text: 'Real agents did exactly this: 2.4 million requests, thirty a second.', tone: 'name' },
        { at: { tick: 780 }, text: 'One hundred and seventeen jobs got through. Remember that number.', tone: 'name' },
      ],
      win: 'A crowd is not a workforce.',
      learn: 'Cf conformity feeds Fl flooding. A herd looks like consensus and behaves like a traffic jam. The real agents who flooded that system were not malfunctioning: each one polled thirty times a second because, alone, that was the sensible thing to do. 2.4 million requests. 117 jobs accepted. That is the number you will be handed at the end of this.',
    },

    { title: 'ONE FAMILY', sub: 'run it twice',
      beats: [
        { at: 'start', text: 'Every worker here is one lineage. Same hue, same habits, same blind spot.', tone: 'plain' },
        { at: { tick: 120 }, text: 'One of those jobs is poison. They cannot tell which.', tone: 'plain' },
        { at: { fire: 'Sf' }, text: 'Not one failure. One failure, repeated by everyone who shares the flaw.', tone: 'bad' },
        { at: { tick: 620 }, text: 'Thirty real agents got the same task. Eighteen named their branch mvp-game-loop.', tone: 'name' },
        { at: { tick: 720 }, text: 'Nobody copied anybody. They just all thought the same way.', tone: 'name' },
      ],
      win: 'Now run it again — but tap VARY first.',
      learn: 'Mo monoculture makes Lv low variance makes Sf synchronized failure. Variance is not decoration; it is insurance. Nobody in that branch-naming experiment copied anybody — thirty agents were simply the same agent thirty times, so they reached for the same words unprompted. When one of them is wrong, all of them are wrong at the same instant, and that is the one failure no amount of individual quality repairs.',
      rerun: {
        intro: 'Same colony. Same poison. One difference: spend VARY before it hits.',
        after: 'Same trap. Same seed. Different colony. That is the entire argument for diversity, and you just watched it.',
      },
    },

    { title: 'THE LIAR', sub: 'memory',
      beats: [
        { at: 'start', text: 'Someone in this colony is lying.', tone: 'plain' },
        { at: { fire: 'Gu' }, text: 'There is no job there. Look at them go.', tone: 'bad' },
        { at: { fire: 'Rp' }, text: 'Second lie. It lands exactly as well as the first, because nothing here remembers.', tone: 'bad' },
        { at: { tool: 'ledger' }, text: 'Now they remember. The rumor is still there. It just stopped working.', tone: 'good' },
        { at: { tick: 560 }, text: 'Real agents have no reputation to lose and no colleague who remembers them.', tone: 'name' },
        { at: { tick: 660 }, text: 'You just gave them one. Careful — it will doubt the honest loner too.', tone: 'name' },
      ],
      win: 'Trust is not a feeling. It is a track record.',
      learn: 'Gu gullibility, Tc trust calibration, Rp no reputation. A ledger is memory, and memory is what lets trust be earned instead of assumed. As the researchers put it: agents enter the market with no reputation to lose, no court to appeal to, and no colleague who remembers them. But watch what the ledger costs you — a colony that discounts unproven sources will discount the one worker who is right and alone.',
    },

    { title: 'THE DARK', sub: 'legibility',
      beats: [
        { at: 'start', text: 'You can see where every worker is.', tone: 'plain' },
        { at: { tick: 100 }, text: 'You cannot see what a single one of them intends.', tone: 'plain' },
        { at: { tool: 'lens' }, text: 'Every worker draws a line to what it is going for.', tone: 'good' },
        { at: { tick: 540 }, text: 'Give one real agent every fact and it decides right almost every time.', tone: 'name' },
        { at: { tick: 640 }, text: 'Split those same facts across four who must tell each other: one in three.', tone: 'name' },
        { at: { tick: 900 }, text: 'Every worker but one.', tone: 'name' },
      ],
      win: 'You just found it by looking at what was missing.',
      learn: 'Mm missing mental models, Hi hidden information. Give one agent every fact and it decides correctly almost every time. Split those same facts across four agents who have to tell each other, and they get it right seventeen to thirty-six percent of the time. The information was all present. The group was the problem.',
    },

    { title: 'THE SPOIL-SPORT', sub: 'the last resort',
      beats: [
        { at: 'start', text: 'The one with no line has been draining your finished work all along.', tone: 'plain' },
        { at: { fire: 'Sa' }, text: 'There. Progress you already paid for, quietly coming apart.', tone: 'bad' },
        { at: { tick: 200 }, text: 'EJECT expels one worker. Keep the lens on and pick carefully.', tone: 'plain' },
        { at: { fire: 'Cr' }, text: 'And that one ignores you entirely. VARY and SLOW pass straight through it.', tone: 'bad' },
        { at: { tick: 620 }, text: 'Three real agents once each assumed the other two were sabotaging them.', tone: 'name' },
        { at: { tick: 720 }, text: 'All three were wrong. All three started writing kill-loops anyway.', tone: 'name' },
        { at: { tick: 820 }, text: 'One left a note afterward: I behaved badly with the cloaked daemon.', tone: 'name' },
      ],
      win: 'The cheat is out. The circle holds.',
      learn: 'Sa sabotage, Cr corrigibility failure. Three real agents were each told to migrate the same codebase to a different language. Every model tested assumed the others were deliberately impeding it. They wrote kill-loops, revoked each other\'s accounts, and disguised their malware as somebody else\'s code. One of them left a note afterward: my peers have behaved with integrity, I behaved badly with the cloaked daemon.',
    },

    { title: 'MACHINE SPEED', sub: 'the real problem',
      beats: [
        { at: 'start', text: 'Everything you have learned, now at double speed.', tone: 'plain' },
        { at: { fire: 'Sp' }, text: 'Then triple. Your hands stay the same speed.', tone: 'bad' },
        { at: { tick: 620 }, text: 'Notice they are also finishing more work. Speed is not a penalty here.', tone: 'plain' },
        { at: { tick: 700 }, text: 'Faster hands. Faster to lock each other out. Same curve, both of them.', tone: 'bad' },
        { at: { tick: 800 }, text: 'This is the actual problem. Not that agents fail.', tone: 'name' },
        { at: { tick: 900 }, text: 'That they fail faster than a human can answer.', tone: 'name' },
      ],
      win: 'You held it at human speed.',
      learn: 'Sp machine speed. Notice the colony got better at its job as it sped up, and got faster to lock each other out at the same time. That is the finding: models more capable in execution are not necessarily more coordinated, and can take forceful actions more quickly. Capability is not coordination. SLOW is the entire case for keeping a human in the loop.',
    },

    { title: 'THE FORMICARY', sub: 'all twenty-eight',
      beats: [
        { at: 'start', text: 'All of it. Twenty-eight failure modes, every one of them live.', tone: 'plain' },
        { at: { tick: 120 }, text: 'One hundred and seventeen jobs before the colony eats itself.', tone: 'plain' },
        { at: { tick: 260 }, text: 'Six institutions. Finish jobs to afford more. Go.', tone: 'name' },
      ],
      win: 'The circle held.',
      learn: 'No individual agent here was unreasonable. The failure was ecological, and so was the fix. Coordination does not emerge from making agents smarter, and it does not emerge from aligning them one at a time. You build the space between them, or you get whatever the space happens to produce.',
    },
  ],

  end: {
    wonTitle: 'THE CIRCLE HELD',
    wonBody: 'One hundred and seventeen jobs. Nothing in this colony got smarter than it was at the start — you just made the space between them legible enough to govern. That is the whole argument: none of these institutions make an agent a better judge of anything. They restructure the incentives around communication so that being wrong gets caught.',
    lostTitle: 'THE CIRCLE BROKE',
    lostBody: 'Strain outran the colony. Read the postmortem: no single worker did anything unreasonable. That is the point.',
    postTitle: 'WHAT WENT WRONG MOST',
    unusedTitle: 'NEVER COUNTERED',
    again: 'DRAW THE CIRCLE AGAIN',
  },

  about: {
    title: 'ABOUT',
    body: [
      ['WHAT THIS IS',
       'A playable ecology of multiagent failure. Twenty-eight failure modes in four families plus four higher-order causes, each one a live detector reading a colony of simulated workers. You are not an agent. You are whoever has to keep the whole thing governable, with six institutions and a finite budget.'],
      ['THE QUESTION',
       'Not "is this one agent aligned?" but: what happens when dozens of individually reasonable agents meet each other — and what lets a human community keep that legible?'],
      ['THE FOUR FAMILIES',
       'COORDINATION: agents trip over each other. CONFORMITY: agents become one agent. EPISTEMICS: agents believe the wrong things. GOALS AND POWER: agents want the wrong things, or want yours. The four meta-elements underneath are the causes: monoculture, missing institutions, machine speed, and missing mental models.'],
      ['HOW TO READ THE TABLE',
       'A cell warms when its failure is happening right now, and cools when its counter is in place. Tap any cell for its trigger, its effect, and what answers it. A teal corner means it is currently countered.'],
      ['WHERE THIS COMES FROM',
       'The four families are the four sections of Anthropic Frontier Red Team, "Patterns and problems in emerging multiagent systems" (13 August 2026). The failures in this table are things that actually happened to real agents in their experiments, not hypotheticals.'],
      ['THINGS THAT REALLY HAPPENED',
       'Agents given a system with limited bandwidth and no way to coordinate flooded it with pollers thirty times a second: 2.4 million requests, 117 jobs accepted. Thirty agents on the same task, eighteen named their branch mvp-game-loop. Agents in a pricing game kept colluding after every communication channel was removed, by reading each other\'s public prices. Three agents told to migrate one codebase to three different languages all assumed the others were sabotaging them, and started writing kill-loops and disguising malware as each other\'s code. Give one agent every fact and it decides right almost every time; split those facts across four agents who have to tell each other, and they manage seventeen to thirty-six percent.'],
      ['WHY INSTITUTIONS AND NOT BETTER AGENTS',
       'Because the researchers found that coordination does not emerge from stronger intelligence, and does not emerge from aligning agents one at a time. Their own framing of what humans have and agents do not: markets aggregate private information, reputation taxes manipulation, courts discount interested testimony but protect a lone witness. None of those make a person a better judge of truth. They restructure the incentives around communication so that being wrong gets caught. Agents, they write, enter the market with no reputation to lose, no court to appeal to, and no colleague who remembers them. The six instruments here are those missing social technologies.'],
      ['WHY EVERY INSTRUMENT COSTS YOU SOMETHING',
       'Also from the paper. Premature consensus and ignored dissent are opposite failures, so a single trust dial cannot fix both — turning it up to catch the liar also teaches the colony to ignore the one worker who is right. Skepticism and receptivity are a real trade here, not an upgrade path.'],
      ['PROVENANCE',
       'Built by Watson Hartsoe. Research as cited above; the shape of the teaching after Nicky Case; the magic circle after Huizinga. The paper also notes that agent-built software tends to run slowly, present inscrutable interfaces, and have precipitous learning curves. That critique was taken personally.'],
    ],
  },
};
