// hlidarendi/tools/bake-trailer.mjs — run the ACTUAL operative construction
// (gunnars-depot operative/ingold.js: shell → openings → interior → services →
// repair) and bake the finished World's members for the page to render.
// This is the whole trailer — chassis, joists, studs, headers, rafters,
// sheathing, the door leaf, glazing, fixtures, water runs — not an abridgement.
import { shell, openings, interior, services, repair } from '/home/user/terrarium/hlidarendi/sources/operative/ingold.js';
import { writeFileSync } from 'node:fs';
const w = shell();
const log = [];
openings(w, log); interior(w, log); services(w, log); repair(w, log);
const all = (w.all ? w.all({}) : w.elements) || [];
const rows = all
  .filter(e => e.lo && e.hi && e.kind !== 'opening')          // openings are cuts, not stuff
  .map(e => [e.id, e.kind, e.material || '', e.layer || '',
    ...e.lo.map(v => +(+v).toFixed(2)), ...e.hi.map(v => +(+v).toFixed(2))]);
const src = `// hlidarendi/src/trailer-members.js — GENERATED by tools/bake-trailer.mjs.
// The finished Ingold World: every committed member of the real construction,
// [id, kind, material, layer, lox, loy, loz, hix, hiy, hiz] in plan inches
// (x across the width, y along the length, z up from the ground datum).
// ${rows.length} members from ${log.length} logged operations.
export const MEMBERS = ${JSON.stringify(rows)};
`;
writeFileSync(new URL('./src/trailer-members.js', import.meta.url), src);
console.log('baked', rows.length, 'members,', src.length, 'bytes');
const kinds = {}; rows.forEach(r => kinds[r[1]] = (kinds[r[1]] || 0) + 1);
console.log(JSON.stringify(kinds));
