create table if not exists public.iii_playtest_sessions (
  id uuid primary key default gen_random_uuid(),
  host_user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  room_code text,
  title text,
  app_version text,
  started_at timestamptz not null default now(),
  ended_at timestamptz,
  metadata_json jsonb not null default '{}'::jsonb
);

create table if not exists public.iii_playtest_events (
  id bigint generated by default as identity primary key,
  session_id uuid not null references public.iii_playtest_sessions(id) on delete cascade,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  peer_id text,
  actor_name text,
  event_type text not null,
  event_at timestamptz not null default now(),
  client_ts bigint,
  seq bigint,
  payload_json jsonb not null default '{}'::jsonb
);

create index if not exists iii_playtest_sessions_host_started_idx on public.iii_playtest_sessions(host_user_id, started_at desc);
create index if not exists iii_playtest_sessions_room_started_idx on public.iii_playtest_sessions(room_code, started_at desc);
create index if not exists iii_playtest_events_session_time_idx on public.iii_playtest_events(session_id, event_at);
create index if not exists iii_playtest_events_user_time_idx on public.iii_playtest_events(user_id, event_at desc);
create index if not exists iii_playtest_events_type_time_idx on public.iii_playtest_events(event_type, event_at desc);

alter table public.iii_playtest_sessions enable row level security;
alter table public.iii_playtest_events enable row level security;
revoke all on public.iii_playtest_sessions from anon;
revoke all on public.iii_playtest_events from anon;
grant select, insert, update on public.iii_playtest_sessions to authenticated;
grant select, insert on public.iii_playtest_events to authenticated;
grant usage, select on sequence public.iii_playtest_events_id_seq to authenticated;

drop policy if exists iii_playtest_sessions_insert_own on public.iii_playtest_sessions;
create policy iii_playtest_sessions_insert_own on public.iii_playtest_sessions for insert to authenticated with check (host_user_id = (select auth.uid()));
drop policy if exists iii_playtest_sessions_select_own on public.iii_playtest_sessions;
create policy iii_playtest_sessions_select_own on public.iii_playtest_sessions for select to authenticated using (host_user_id = (select auth.uid()));
drop policy if exists iii_playtest_sessions_update_own on public.iii_playtest_sessions;
create policy iii_playtest_sessions_update_own on public.iii_playtest_sessions for update to authenticated using (host_user_id = (select auth.uid())) with check (host_user_id = (select auth.uid()));

drop policy if exists iii_playtest_events_insert_own on public.iii_playtest_events;
create policy iii_playtest_events_insert_own on public.iii_playtest_events for insert to authenticated with check (user_id = (select auth.uid()));
drop policy if exists iii_playtest_events_select_own_or_host on public.iii_playtest_events;
create policy iii_playtest_events_select_own_or_host on public.iii_playtest_events for select to authenticated using (
  user_id = (select auth.uid())
  or exists (
    select 1 from public.iii_playtest_sessions s
    where s.id = iii_playtest_events.session_id
      and s.host_user_id = (select auth.uid())
  )
);
